name = "GenieCache"
uuid = "dec2e30d-c3e4-4386-8d4a-5e4ccb406543"
authors = ["Adrian Salceanu <adrian.salceanu@gmail.com> and contributors"]
version = "1.0.1"

[deps]
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[compat]
Genie = "5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
